"""add category and comment to spending_logs

Revision ID: 09575f4ad66c
Revises: 
Create Date: 2025-06-08 13:18:37.121150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09575f4ad66c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending_logs', sa.Column('category', sa.String(), nullable=True))
    op.add_column('spending_logs', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending_logs', 'comment')
    op.drop_column('spending_logs', 'category')
    # ### end Alembic commands ###
