"""Add source column to NudgeLog

Revision ID: aea6b3a8d86e
Revises: 09575f4ad66c
Create Date: 2025-07-10 11:11:45.096933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea6b3a8d86e'
down_revision: Union[str, None] = '09575f4ad66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nudge_logs', sa.Column('voice_enabled', sa.Boolean(), nullable=True))
    op.add_column('nudge_logs', sa.Column('source', sa.String(), nullable=True))
    op.add_column('users', sa.Column('voice_feature_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'voice_feature_enabled')
    op.drop_column('nudge_logs', 'source')
    op.drop_column('nudge_logs', 'voice_enabled')
    # ### end Alembic commands ###
